[package]
name = "sdkwork-api-dezhou-assembly"
edition.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-dezhou application HTTP plane."

[lib]
name = "sdkwork_api_dezhou_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork_dezhou_service_host.workspace = true
sdkwork_routes_table_app_api = { workspace = true }
sdkwork_routes_table_backend_api = { workspace = true }

[dev-dependencies]
sdkwork_dezhou_table_repository_sqlx.workspace = true
sdkwork_dezhou_table_service.workspace = true
sdkwork-web-core.workspace = true
tokio.workspace = true
tower = { version = "0.5", features = ["util"] }
